---
# Players can't get another kit till they die
one-kit-per-life: true
# Players can claim another kit if they relog(only if one-kit-per-life is true)
reset-on-logout: true
# Start adding items from the first slot of inventory no matter what, will delete the present item at slot
start-from-first: false
# Clears player inventory before adding the kit
clear-inventory: false
# Clears player effect(s) before adding the kit
clear-effect: false
# Text on sign for kit form (case-insensitive)
text-on-sign: "[KitUI]"
...
